<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageVersion>1.2</PackageVersion>
    <Authors>Pratama Bayu Widagdo</Authors>
    <Description>Hosting management for .Net</Description>
    <PackageId>Hosting.Management</PackageId>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType></DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Polly" Version="8.6.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
  </ItemGroup>
</Project>